// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: proto/gameManager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequireNewGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GameType int32 `protobuf:"varint,2,opt,name=GameType,proto3" json:"GameType,omitempty"`
}

func (x *RequireNewGameRequest) Reset() {
	*x = RequireNewGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireNewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireNewGameRequest) ProtoMessage() {}

func (x *RequireNewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireNewGameRequest.ProtoReflect.Descriptor instead.
func (*RequireNewGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{0}
}

func (x *RequireNewGameRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RequireNewGameRequest) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

type RequireNewGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	OpponentID int32  `protobuf:"varint,2,opt,name=OpponentID,proto3" json:"OpponentID,omitempty"`
}

func (x *RequireNewGameResponse) Reset() {
	*x = RequireNewGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireNewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireNewGameResponse) ProtoMessage() {}

func (x *RequireNewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireNewGameResponse.ProtoReflect.Descriptor instead.
func (*RequireNewGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{1}
}

func (x *RequireNewGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequireNewGameResponse) GetOpponentID() int32 {
	if x != nil {
		return x.OpponentID
	}
	return 0
}

type CancelRequireGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GameType int32 `protobuf:"varint,2,opt,name=GameType,proto3" json:"GameType,omitempty"`
}

func (x *CancelRequireGameRequest) Reset() {
	*x = CancelRequireGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequireGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequireGameRequest) ProtoMessage() {}

func (x *CancelRequireGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequireGameRequest.ProtoReflect.Descriptor instead.
func (*CancelRequireGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequireGameRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CancelRequireGameRequest) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

type CancelRequireGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CancelRequireGameResponse) Reset() {
	*x = CancelRequireGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequireGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequireGameResponse) ProtoMessage() {}

func (x *CancelRequireGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequireGameResponse.ProtoReflect.Descriptor instead.
func (*CancelRequireGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequireGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcceptNewGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	GameType   int32 `protobuf:"varint,2,opt,name=GameType,proto3" json:"GameType,omitempty"`
	OpponentID int32 `protobuf:"varint,3,opt,name=OpponentID,proto3" json:"OpponentID,omitempty"`
}

func (x *AcceptNewGameRequest) Reset() {
	*x = AcceptNewGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptNewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNewGameRequest) ProtoMessage() {}

func (x *AcceptNewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNewGameRequest.ProtoReflect.Descriptor instead.
func (*AcceptNewGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptNewGameRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AcceptNewGameRequest) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *AcceptNewGameRequest) GetOpponentID() int32 {
	if x != nil {
		return x.OpponentID
	}
	return 0
}

type AcceptNewGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	GameID  int32  `protobuf:"varint,2,opt,name=GameID,proto3" json:"GameID,omitempty"`
	Black   bool   `protobuf:"varint,3,opt,name=Black,proto3" json:"Black,omitempty"`
}

func (x *AcceptNewGameResponse) Reset() {
	*x = AcceptNewGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptNewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNewGameResponse) ProtoMessage() {}

func (x *AcceptNewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNewGameResponse.ProtoReflect.Descriptor instead.
func (*AcceptNewGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptNewGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AcceptNewGameResponse) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *AcceptNewGameResponse) GetBlack() bool {
	if x != nil {
		return x.Black
	}
	return false
}

type ShootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID int32 `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`
	UserID int32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Black  bool  `protobuf:"varint,3,opt,name=Black,proto3" json:"Black,omitempty"`
	Row    int32 `protobuf:"varint,4,opt,name=Row,proto3" json:"Row,omitempty"`
	Col    int32 `protobuf:"varint,5,opt,name=Col,proto3" json:"Col,omitempty"`
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{6}
}

func (x *ShootRequest) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *ShootRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ShootRequest) GetBlack() bool {
	if x != nil {
		return x.Black
	}
	return false
}

func (x *ShootRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ShootRequest) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type ShootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Row     int32  `protobuf:"varint,2,opt,name=Row,proto3" json:"Row,omitempty"`
	Col     int32  `protobuf:"varint,3,opt,name=Col,proto3" json:"Col,omitempty"`
	Result  int32  `protobuf:"varint,4,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ShootResponse) Reset() {
	*x = ShootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootResponse) ProtoMessage() {}

func (x *ShootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootResponse.ProtoReflect.Descriptor instead.
func (*ShootResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{7}
}

func (x *ShootResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShootResponse) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ShootResponse) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *ShootResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type RequireFirstShootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID int32 `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`
}

func (x *RequireFirstShootRequest) Reset() {
	*x = RequireFirstShootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireFirstShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireFirstShootRequest) ProtoMessage() {}

func (x *RequireFirstShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireFirstShootRequest.ProtoReflect.Descriptor instead.
func (*RequireFirstShootRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{8}
}

func (x *RequireFirstShootRequest) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

type RequireFirstShootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Row     int32  `protobuf:"varint,2,opt,name=Row,proto3" json:"Row,omitempty"`
	Col     int32  `protobuf:"varint,3,opt,name=Col,proto3" json:"Col,omitempty"`
}

func (x *RequireFirstShootResponse) Reset() {
	*x = RequireFirstShootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireFirstShootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireFirstShootResponse) ProtoMessage() {}

func (x *RequireFirstShootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireFirstShootResponse.ProtoReflect.Descriptor instead.
func (*RequireFirstShootResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{9}
}

func (x *RequireFirstShootResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequireFirstShootResponse) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *RequireFirstShootResponse) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type InformTimeOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID int32 `protobuf:"varint,1,opt,name=GameID,proto3" json:"GameID,omitempty"`
	UserID int32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Black  bool  `protobuf:"varint,3,opt,name=Black,proto3" json:"Black,omitempty"`
}

func (x *InformTimeOutRequest) Reset() {
	*x = InformTimeOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformTimeOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformTimeOutRequest) ProtoMessage() {}

func (x *InformTimeOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformTimeOutRequest.ProtoReflect.Descriptor instead.
func (*InformTimeOutRequest) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{10}
}

func (x *InformTimeOutRequest) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *InformTimeOutRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *InformTimeOutRequest) GetBlack() bool {
	if x != nil {
		return x.Black
	}
	return false
}

type InformTimeOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *InformTimeOutResponse) Reset() {
	*x = InformTimeOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gameManager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformTimeOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformTimeOutResponse) ProtoMessage() {}

func (x *InformTimeOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gameManager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformTimeOutResponse.ProtoReflect.Descriptor instead.
func (*InformTimeOutResponse) Descriptor() ([]byte, []int) {
	return file_proto_gameManager_proto_rawDescGZIP(), []int{11}
}

func (x *InformTimeOutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gameManager_proto protoreflect.FileDescriptor

var file_proto_gameManager_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x15, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x52, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x4f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x18, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x35, 0x0a, 0x19, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x6a, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x4f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x4f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x5f, 0x0a,
	0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x22, 0x78,
	0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x6f, 0x6c, 0x22, 0x65, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x6f,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x43, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x32, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x6f,
	0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x6f, 0x6c, 0x22, 0x5c,
	0x0a, 0x14, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x22, 0x31, 0x0a, 0x15,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x9c, 0x03, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x43, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x4e, 0x65, 0x77, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x12, 0x0d, 0x2e,
	0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x68,
	0x6f, 0x6f, 0x74, 0x12, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x68, 0x6f,
	0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x15, 0x2e,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x6d,
	0x65, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gameManager_proto_rawDescOnce sync.Once
	file_proto_gameManager_proto_rawDescData = file_proto_gameManager_proto_rawDesc
)

func file_proto_gameManager_proto_rawDescGZIP() []byte {
	file_proto_gameManager_proto_rawDescOnce.Do(func() {
		file_proto_gameManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gameManager_proto_rawDescData)
	})
	return file_proto_gameManager_proto_rawDescData
}

var file_proto_gameManager_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_gameManager_proto_goTypes = []interface{}{
	(*RequireNewGameRequest)(nil),     // 0: RequireNewGameRequest
	(*RequireNewGameResponse)(nil),    // 1: RequireNewGameResponse
	(*CancelRequireGameRequest)(nil),  // 2: CancelRequireGameRequest
	(*CancelRequireGameResponse)(nil), // 3: CancelRequireGameResponse
	(*AcceptNewGameRequest)(nil),      // 4: AcceptNewGameRequest
	(*AcceptNewGameResponse)(nil),     // 5: AcceptNewGameResponse
	(*ShootRequest)(nil),              // 6: ShootRequest
	(*ShootResponse)(nil),             // 7: ShootResponse
	(*RequireFirstShootRequest)(nil),  // 8: RequireFirstShootRequest
	(*RequireFirstShootResponse)(nil), // 9: RequireFirstShootResponse
	(*InformTimeOutRequest)(nil),      // 10: InformTimeOutRequest
	(*InformTimeOutResponse)(nil),     // 11: InformTimeOutResponse
}
var file_proto_gameManager_proto_depIdxs = []int32{
	0,  // 0: GameManager.RequireNewGame:input_type -> RequireNewGameRequest
	2,  // 1: GameManager.CancelRequireGame:input_type -> CancelRequireGameRequest
	4,  // 2: GameManager.AcceptNewGame:input_type -> AcceptNewGameRequest
	6,  // 3: GameManager.Shoot:input_type -> ShootRequest
	8,  // 4: GameManager.RequireFirstShoot:input_type -> RequireFirstShootRequest
	10, // 5: GameManager.InformTimeOut:input_type -> InformTimeOutRequest
	1,  // 6: GameManager.RequireNewGame:output_type -> RequireNewGameResponse
	3,  // 7: GameManager.CancelRequireGame:output_type -> CancelRequireGameResponse
	5,  // 8: GameManager.AcceptNewGame:output_type -> AcceptNewGameResponse
	7,  // 9: GameManager.Shoot:output_type -> ShootResponse
	9,  // 10: GameManager.RequireFirstShoot:output_type -> RequireFirstShootResponse
	11, // 11: GameManager.InformTimeOut:output_type -> InformTimeOutResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gameManager_proto_init() }
func file_proto_gameManager_proto_init() {
	if File_proto_gameManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gameManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireNewGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireNewGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequireGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequireGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptNewGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptNewGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireFirstShootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireFirstShootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformTimeOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gameManager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformTimeOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gameManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gameManager_proto_goTypes,
		DependencyIndexes: file_proto_gameManager_proto_depIdxs,
		MessageInfos:      file_proto_gameManager_proto_msgTypes,
	}.Build()
	File_proto_gameManager_proto = out.File
	file_proto_gameManager_proto_rawDesc = nil
	file_proto_gameManager_proto_goTypes = nil
	file_proto_gameManager_proto_depIdxs = nil
}
